---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directories:
      - /envs/plt/
      - /modules/iam/
      - /modules/kms/
    schedule:
      interval: daily
    open-pull-requests-limit: 10
