---
AWSTemplateFormatVersion: 2010-09-09
Description: IAM user with administrator access
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W1011
Parameters:
  AdministratorUserName:
    Description: Set the administrator user name.
    Type: String
    Default: local-administrator
  InitialPassword:
    Description: Set the initial password for the administrator user.
    Type: String
    NoEcho: true
Resources:
  AdministratorUser:
    Type: AWS::IAM::User
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      UserName: !Ref AdministratorUserName
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      LoginProfile:
        Password: !Ref InitialPassword
        PasswordResetRequired: true
      Tags:
        - Key: Name
          Value: !Ref AdministratorUserName
Outputs:
  AdministratorUserArn:
    Value: !GetAtt AdministratorUser.Arn
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AdministratorUserArn
