---
AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket and DynamoDB table for Terraform
Parameters:
  ResourcePrefix:
    Description: Set the resource prefix.
    Type: String
    Default: tfstate
Resources:
  # trivy:ignore:AVD-AWS-0089
  # trivy:ignore:AVD-AWS-0132
  TerraformStateS3Bucket:
    Type: AWS::S3::Bucket
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_18
            comment: Access logs are handled by centralized logging buckets.
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${ResourcePrefix}-${AWS::Region}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Move-to-Intelligent-Tiering-after-0day
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
            NoncurrentVersionExpiration:
              NoncurrentDays: 1
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
      Tags:
        - Key: Name
          Value: !Sub ${ResourcePrefix}-${AWS::Region}-${AWS::AccountId}
        - Key: Application
          Value: Terraform
Outputs:
  TerraformStateS3Bucket:
    Value: !Ref TerraformStateS3Bucket
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-TerraformStateS3Bucket
