---
AWSTemplateFormatVersion: 2010-09-09
Description: GuardDuty and EventBridge
Parameters:
  SystemName:
    Description: Set the system name.
    Type: String
  EnvType:
    Description: Set the environment type.
    Type: String
  SnsTopicArn:
    Description: Set the SNS topic ARN.
    Type: String
  FindingPublishingFrequency:
    Description: Set the finding publishing frequency.
    Type: String
    Default: SIX_HOURS
    AllowedValues:
      - FIFTEEN_MINUTES
      - ONE_HOUR
      - SIX_HOURS
Resources:
  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
      FindingPublishingFrequency: !Ref FindingPublishingFrequency
      DataSources:
        S3Logs:
          Enable: true
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-guardduty-detector
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
  EventBridge:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${SystemName}-${EnvType}-guardduty-eventbridge
      EventPattern:
        source:
          - aws.guardduty
        detail-type:
          - GuardDuty Finding
      Targets:
        - Arn: !Ref SnsTopicArn
          Id:
            Fn::Select:
              - 5
              - Fn::Split:
                  - ':'
                  - !Ref SnsTopicArn
Outputs:
  GuardDutyDetector:
    Value: !Ref GuardDutyDetector
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-GuardDutyDetector
  EventBridge:
    Value: !Ref EventBridge
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-EventBridge
