---
AWSTemplateFormatVersion: 2010-09-09
Description: GuardDuty Detector
Parameters:
  SystemName:
    Description: Set the system name.
    Type: String
  EnvType:
    Description: Set the environment type.
    Type: String
  FindingPublishingFrequency:
    Description: Set the finding publishing frequency.
    Type: String
    Default: SIX_HOURS
    AllowedValues:
      - FIFTEEN_MINUTES
      - ONE_HOUR
      - SIX_HOURS
Resources:
  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
      FindingPublishingFrequency: !Ref FindingPublishingFrequency
      DataSources:
        S3Logs:
          Enable: true
        MalwareProtection:
          ScanEc2InstanceWithFindings:
            EbsVolumes: true
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-guardduty-detector
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
Outputs:
  GuardDutyDetector:
    Value: !Ref GuardDutyDetector
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-GuardDutyDetector
