---
name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      workflow:
        required: true
        type: choice
        options:
          - lint-and-scan
          - upgrade
        description: Choose the workflow to run
        default: lint-and-scan
permissions:
  contents: write
  pull-requests: write
jobs:
  cloudformation-lint:
    if: >
      github.event_name == 'push'
      || github.event_name == 'pull_request'
      || (github.event_name == 'workflow_dispatch' && inputs.workflow == 'lint-and-scan')
    uses: dceoy/gh-actions-for-devops/.github/workflows/aws-cloudformation-lint.yml@main
    with:
      search-path: .
      python-version: 3.x
      cfn-lint-options: --ignore-checks W1011 --template
  terraform-lint-and-scan:
    if: >
      github.event_name == 'push'
      || (
        github.event_name == 'pull_request'
        && (! startswith(github.head_ref, 'dependabot/terraform/'))
        && (! startswith(github.head_ref, 'renovate/'))
      ) || (github.event_name == 'workflow_dispatch' && inputs.workflow == 'lint-and-scan')
    uses: dceoy/gh-actions-for-devops/.github/workflows/terraform-lint-and-scan.yml@main
    with:
      search-path: .
      terraform-version: latest
  terraform-lock-files-upgrade:
    if: >
      (
        github.event_name == 'pull_request'
        && (startswith(github.head_ref, 'dependabot/terraform/') || startswith(github.head_ref, 'renovate/'))
      ) || (github.event_name == 'workflow_dispatch' && inputs.workflow == 'upgrade')
    uses: dceoy/gh-actions-for-devops/.github/workflows/terraform-lock-files-upgrade-and-pr-merge.yml@main
    with:
      terraform-working-directories: envs/plt
      terraform-version: latest
      search-path-for-lint-and-scan: .
      merge-pr: ${{ github.event_name == 'pull_request' }}
  dependabot-auto-merge:
    if: >
      github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    needs:
      - cloudformation-lint
      - terraform-lint-and-scan
    uses: dceoy/gh-actions-for-devops/.github/workflows/dependabot-auto-merge.yml@main
    with:
      unconditional: true
  open-pr-aggregate:
    if: >
      github.event_name == 'pull_request' && startswith(github.head_ref, 'dependabot/terraform/')
    uses: dceoy/gh-actions-for-devops/.github/workflows/github-open-pr-aggregate.yml@main
    with:
      pr-branch-prefix: dependabot/terraform/
