---
name: Lint, scan, and formatting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      workflow:
        required: true
        type: choice
        options:
          - lint
          - format
        description: Choose the workflow to run
        default: lint
permissions:
  contents: write
  pull-requests: write
jobs:
  cfn-lint:
    if: >
      github.event_name == 'push'
      || github.event_name == 'pull_request'
      || (github.event_name == 'workflow_dispatch' && inputs.workflow == 'lint')
    uses: dceoy/gh-actions-for-devops/.github/workflows/aws-cloudformation-lint.yml@main
    with:
      search-path: .
      python-version: 3.x
      cfn-lint-options: --ignore-checks W1011 --template
  tf-lint-and-scan:
    if: >
      github.event_name == 'push'
      || github.event_name == 'pull_request'
      || (github.event_name == 'workflow_dispatch' && inputs.workflow == 'lint')
    uses: dceoy/gh-actions-for-devops/.github/workflows/terraform-lint-and-scan.yml@main
    with:
      search-path: .
      terraform-version: latest
  tf-format:
    if: >
      github.event_name == 'pull_request'
      || (github.event_name == 'workflow_dispatch' && inputs.workflow == 'format')
    uses: dceoy/gh-actions-for-devops/.github/workflows/terraform-format-and-pr.yml@main
    with:
      search-path: .
      terraform-version: latest
  dependabot-auto-merge:
    if: >
      github.event_name == 'pull_request'
    needs:
      - cfn-lint
      - tf-lint-and-scan
      - tf-format
    uses: dceoy/gh-actions-for-devops/.github/workflows/dependabot-auto-merge.yml@main
